Part 1 : In-Memory SQLite Databases using Python

In [2]:
!pip install sqlite3

ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for sqlite3

In [3]:
import sqlite3
import pandas as pd 

connection = sqlite3.connect(':memory:')

cursor = connection.cursor()

In [4]:
create_table_query = '''
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    STATISTICS_marks INTEGER,
    python_marks INTEGER,
    ml_marks INTEGER,
    dl_marks INTEGER
);
'''

cursor.execute(create_table_query)
print("Students table created.")

Students table created.

In [5]:
insert_data_query= '''
INSERT INTO Students (name, age, statistics_marks, python_marks, ml_marks, dl_marks)
VALUES
('Mazen', 20, 85, 90, 88, 92),
('Khaled', 21, 75, 78, 82, 85),
('Hamza', 22, 88, 91, 84, 89),
('Achraf', 19, 92, 89, 95, 91),
('Abdo', 23, 80, 87, 85, 90);
'''

cursor.execute(insert_data_query)
connection.commit()

print("Data inserted into the Student table.")

Data inserted into the Student table.

In [6]:
query = "SELECT * FROM Students;"
df = pd.read_sql(query, connection)
print("Querying the Students table:")
df

Querying the Students table:

   id    name  age  STATISTICS_marks  python_marks  ml_marks  dl_marks
0   1   Mazen   20                85            90        88        92
1   2  Khaled   21                75            78        82        85
2   3   Hamza   22                88            91        84        89
3   4  Achraf   19                92            89        95        91
4   5    Abdo   23                80            87        85        90

In [7]:
update_query = "UPDATE Students SET python_marks = 95 WHERE name = 'Khaled'"
cursor.execute(update_query)
connection.commit()

print("Updated Khaled's Python grade")

Updated Khaled's Python grade

In [8]:
updated_df = pd.read_sql(query, connection)

print("Updated data")
updated_df

Updated data

   id    name  age  STATISTICS_marks  python_marks  ml_marks  dl_marks
0   1   Mazen   20                85            90        88        92
1   2  Khaled   21                75            95        82        85
2   3   Hamza   22                88            91        84        89
3   4  Achraf   19                92            89        95        91
4   5    Abdo   23                80            87        85        90

In [9]:
cursor.close()
connection.close()

Part 2 : Connecting MySQL Database to Python